FROM python:3.11-slim

WORKDIR /app

RUN pip install requests

# Copy script into container
COPY query_occupancy.py main.py
COPY room_list.txt room_list.txt
COPY entrypoint_occupancy.sh /entrypoint.sh

# Run the script and write output
CMD ["/entrypoint.sh"]
